spring.application.name=ats.springBoot


server.port=8080

app.base-url=${APP_BASE_URL:http://localhost:8080}

app.mail.host=${MAIL_HOST:smtp.gmail.com}
app.mail.port=${MAIL_PORT:587}
app.mail.username=${MAIL_USERNAME:}
app.mail.password=${MAIL_PASSWORD:}
app.mail.from=${MAIL_FROM:${MAIL_USERNAME:}}

spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EnglishLearningDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

spring.jpa.open-in-view=false